export { GlobalStyles } from './GlobalStyles'
export { Header } from './Header/Header'
export { Badge } from './Badge'
export { Category } from './Category/Category'
export { Footer } from './Footer/Footer'